C2D:
  search: "macbook 3,1"
  processor: .+(Core2).+(T7500)
  name: "MacBook Late 2007, Core2 Duo T7500 @ 2.20 GHz"

C2D_P8800:
  search: "macbookpro 5,3"
  processor: .+(Core2).+(P8800)
  name: "MacBook Pro 15 Mid 2009, Core2 Duo P8800 @ 2.66 GHz"
    
C2D_T9600:
  search: "macbookpro 5,3"
  processor: .+(Core2).+(T9600)
  name: "MacBook Pro 15 Mid 2009, Core2 Duo T9600 @ 2.80 GHz"
  
C2D_U9400:
  search: "macbookair 3,1"
  processor: .+(Core2).+(U9400)
  name: "MacBook Air 11 Late 2010, Core2 Duo U9400 @ 1.40 GHz"
    
C2D_U9600:
  search: "macbookair 3,1"
  processor: .+(Core2).+(U9600)
  name: "MacBook Air 11 Late 2010, Core2 Duo U9600 @ 1.60 GHz"

C2D_L9400:
  search: "macbookair 3,2"
  processor: .+(Core2).+(L9400)
  name: "MacBook Air 13 Late 2010, Core2 Duo L9400 @ 1.86 GHz"

C2D_L9600:
  search: "macbookair 3,2"
  processor: .+(Core2).+(L9600)
  name: "MacBook Air 13 Late 2010, Core2 Duo L9600 @ 2.13 GHz"

i5_520:
  search: "macbookpro 6,2"
  processor: .+(i5).+(520)
  name: "MacBook Pro 15 Early 2010, Core i5 520 @ 2.40 GHz" 
    
i5_540:
  search: "macbookpro 6,2"
  processor: .+(i5).+(540)
  name: "MacBook Pro 15 Early 2010, Core i5 540 @ 2.53 GHz" 
    
i7_620:
  search: "macbookpro 6,2"
  processor: .+(i7).+(620)
  name: "MacBook Pro 15 Early 2010, Core i7 620 @ 2.66 GHz"

i7_640:
  search: "macbookpro 6,2"
  processor: .+(i7).+(640)
  name: "MacBook Pro 15 Early 2010, Core i7 640 @ 2.80 GHz"
